### ISSUE TITLE
Dockerize this app

### ISSUE THREAD

**Issue by jhsu802701** [rubyforgood/rubyforgood.org#29]
Dockerizing this app would speed up the onboarding process and head off the infamous "but it works on my machine" problem.

**Comment by meg-gutshall** [comment]
Hey @jhsu802701! Let's talk about this issue more as well because it's so closely related with Issue #30.

If you go to the "Actions" tab on this repo, there's a Jekyll workflow to package a Jekyll site using the jekyll/builder Docker image. Here's a link to the code: ]https://github.com/actions/starter-workflows/blob/7b9e3b68582d04b65cb955fb75c48342450b7f3b/ci/jekyll.yml](https://github.com/actions/starter-workflows/blob/7b9e3b68582d04b65cb955fb75c48342450b7f3b/ci/jekyll.yml)

Is something like this what you had in mind?

**Comment by jhsu802701** [comment]
I use Docker for the development environment, not the production environment.  In fact, I don't rely on my local machine's host environment as my development environment.  Not being able to reset the development environment willy-nilly is a deal breaker for me.

An example of how I use Docker is at https://github.com/jhsu802701/rubymn2 .

**Comment by jhsu802701** [comment]
The page you linked to is an idea for continuous integration rather than Dockerizing for development.

**Comment by meg-gutshall** [comment]
Can you tell me what this does then?

```
name: Jekyll site CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"
```
